title: Bayesian model selection in complex regression contexts
description: A package with mode jumping MCMC and its modifications for Bayesian variable selection and model averaging in various regression contexts
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
